### ISSUE TITLE
gyp ERR! on npm install

### ISSUE THREAD

**Issue by jshcd** [ging/fiware-pep-proxy#11]
Hello Álvaro,

I have tried to install the Pep Proxy Wilma over an Ubuntu Server 14.04 and I always get the same problem when I run the following command:

`npm install`

The error I get is the following one:

`gyp: Call to 'node -e "reqyre('nan')"' returned exit 127. while trying to load binding.gyp.`

Do you have an idea about what can be happening?

Thanks in advance.

**Comment by aalonsog** [comment]
Hi, 

it seems you have a problem with some dependencies. But I don’t know which exactly… maybe you can try to google your issue.

BR
-- 
Álvaro

**Comment by aalonsog** [comment]
Closed due to inactivity

**Comment by aonurdemir** [comment]
sudo apt-get install nodejs-legacy
npm install
