### ISSUE TITLE
HTTPS port not working in v7.9

### ISSUE THREAD

**Issue by ravaga** [ging/fiware-pep-proxy#112]
Hi, if HTTPS is enabled, the HTTPS port is not working in Docker when it's configured via the environment variable PEP_PROXY_HTTPS_PORT. For that reason, the PEP Proxy sets the port to the default 443 value, and throws an error:

`pep wilma ERROR: Server - Caught exception: Error: listen EACCES: permission denied 0.0.0.0:443`

I think the problem is in the file **/lib/config_service.js**, the file where the configuration values are assigned.

**Comment by apozohue10** [comment]
Solved with PR 113
