### ISSUE TITLE
Add support for Authzforce 4.4.x

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-pep-proxy#17]
The current release of Authzforce and the one available on the [catalogue](http://catalogue.fiware.org/enablers/authorization-pdp-authzforce) is version 4.4.1, but both idm and pep-wilma only work with version 4.2.0, as there are some changes in the urls and xml.  Please consider adding support for the new Authzforce version.  The main change for pep-wilma seems to be that the response xml of the pdp has changed from:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Response xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
   <Result>
       <Decision>Permit</Decision>
       <Status>
           <StatusCode Value="urn:oasis:names:tc:xacml:1.0:status:ok" />
       </Status>
   </Result>
</Response>
```

to:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns5:Response xmlns:ns2="http://authzforce.github.io/core/xmlns/pdp/3.6" xmlns:ns3="http://authzforce.github.io/rest-api-model/xmlns/authz/4" xmlns:ns4="http://www.w3.org/2005/Atom" xmlns:ns5="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:ns6="http://authzforce.github.io/pap-dao-file/xmlns/properties/3.6">
  <ns5:Result>
    <ns5:Decision>Permit</ns5:Decision>
  </ns5:Result>
</ns5:Response>
```

Also, this request is hardcoded to use https in [lib/azf.js](https://github.com/ging/fiware-pep-proxy/blob/master/lib/azf.js#L187).

Thanks.

**Comment by aalonsog** [comment]
Thanks! We have added this as a new feature fot the GE.

BR
