### ISSUE TITLE
Add latest release tag (5.3) to Docker Hub repository

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-pep-proxy#21]
Please, add the latest release (5.3) to the tags available in the Docker Hub repository.

**Comment by federicofdez** [comment]
Hello @dmabtrg ,

Thank you for writing. It will be ready within the next few days.

Regards,
Federico

**Comment by dmabtrg** [comment]
Hi, is there any news on this?  There's a `5.3.1` tag on the hub, but the version installed in that image is `5.2.1`, not `5.3.1`.

**Comment by aalonsog** [comment]
Yes, sorry. I'm going to fix it ASAP
