### ISSUE TITLE
NPM install exits with code 1

### ISSUE THREAD

**Issue by koenkarsten** [ging/fiware-pep-proxy#22]
When running `npm install` with the latest version of node (6.3.1) it crashes, with quite an extensive log (have a look in the attachments).

[dump.txt](https://github.com/ging/fiware-pep-proxy/files/410995/dump.txt)

This crash seems to occur due to an old dependency..

**Comment by koenkarsten** [comment]
Proposing fix in Pull Request #23

**Comment by aalonsog** [comment]
Accepted, thanks!
