### ISSUE TITLE
Authzforce calls harcoded to use HTTPS.

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-pep-proxy#25]
When pep wilma sends data to Authzforce, it uses HTTPS as default (see [lib/azf.js#L198](https://github.com/ging/fiware-pep-proxy/blob/master/lib/azf.js#L198)).  If Authzforce is not configured to listen to HTTPS requests (like the [official authzforce docker image](https://hub.docker.com/r/fiware/authzforce-ce-server/)) this results in the following error, as a result of xml2json not being able to transform the response from the Authzforce server:

```
ERROR: Server - Caught exception: Error: There are errors in your xml file: syntax error
```

Maybe this should be configurable, as other Authzforce options are.

Thanks.

**Comment by aalonsog** [comment]
Done, thanks!
