### ISSUE TITLE
Ambiguity of config.pep_port vs config.https.port

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-pep-proxy#28]
When I have 
```javascript
config.pep_port = 80;

// Set this var to undefined if you don't want the server to listen on HTTPS
config.https = {
    enabled: true,
    ...
    port: 443
};
```
is the PEP proxy supposed to listen on both ports http/80 and http**s**/443 or just the **https** one? If on both ports, how do I configure to listen to http**s** only?
The documentation should clarify that. Thanks.

**Comment by aalonsog** [comment]
Just in one port. Clarification in https://github.com/ging/fiware-pep-proxy/commit/718db22e8e65a7e146a372ec9303c82249dc67e7
