### ISSUE TITLE
Docker image tagged 5.3.1 is actually pep-proxy v5.2.1

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-pep-proxy#29]
I retrieved Docker image tagged 5.3.1 from Docker hub two days ago, and I realized this is actually pep-proxy v5.2.1 inside. **Could you fix the tag on Docker hub or make a new Docker release?**
Thanks.

**Comment by aalonsog** [comment]
It should be fixed 
https://hub.docker.com/r/fiware/pep-proxy/tags/
