### ISSUE TITLE
Cannot parse XACML response from Authzforce because of arbitrary XML namespace prefixes

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-pep-proxy#31]
In `lib/azf.js`, XACML response (from authzforce) parsing by xml2json keeps the namespace prefixes in the generated JSON keys, which breaks the extraction of the XACML Decision. Namespace prefixes are arbitrary and may change without notice. What matters is the namespace URI they are associated with (in the 'xmlns' attribute) which is always the XACML namespace. For example, the XACML Response may have `xmlns:ns4="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"`  and so a `ns4:Decision` element at some point. Then later, it may have `xmlns:ns6="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"` and so `ns6:Decision`, etc.
One solution is to use NPM package 'xml2js' which can strip namespace prefixes while converting to JSON and therefore remove any dependency on the namespace prefix.

On the long-term, I would recommend replacing xml2json with 'xml2js' for all XML parsing since it handles XML complexity better (more features and flexibility).

**Comment by aalonsog** [comment]
Thanks!!
