### ISSUE TITLE
Invalid XACML Request to the PDP if the authenticated user has no role

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-pep-proxy#32]
The XACML request produced is invalid if the authenticated user has no role (empty roles array). Indeed, in this case, the subject-role Attribute element does not have any AttributeValue, and this is rejected by the PDP because it is not valid per XACML schema. The solution is just to avoid including the subject-role Attribute itself in the Request when there is not any role to put in it.

**Comment by aalonsog** [comment]
Thanks again!
