### ISSUE TITLE
Cannot import name _uuid_generate_random

### ISSUE THREAD

**Issue by sickboy93** [ging/fiware-pep-proxy#42]
Hi everyone, I've got Wilma and KeyRock on the same VM, this is my config.js
```
config.account_host = 'http://localhost';

config.keystone_host = 'localhost';
config.keystone_port = 5000;

config.username = 'sandro';
config.password = 'sandro';

```
`sandro` is the user I created, give him role of admin and then generate the token. When I launch the PEP proxy:

```
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications   File "/home/ubuntu/keystone/.venv/local/lib/python2.7/site-packages/stevedore/extension.py", line 170, in _load_plugins
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications     self._on_load_failure_callback(self, ep, err)
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications   File "/home/ubuntu/keystone/.venv/local/lib/python2.7/site-packages/stevedore/driver.py", line 50, in _default_on_load_failure
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications     raise err
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications ImportError: cannot import name _uuid_generate_random
2018-01-28 15:07:14.280 24574 TRACE keystone.notifications 
2018-01-28 15:07:14.866 24574 WARNING keystone.common.wsgi [-] Authorization failed. The request you have made requires authentication. from 127.0.0.1
2018-01-28 15:07:14.921 24574 INFO eventlet.wsgi.server [-] 127.0.0.1 - - [28/Jan/2018 15:07:14] "POST /v3/auth/tokens HTTP/1.1" 401 328 8.502280
```

I still don't have configured AuthZ and put any app, I had initially google.es as the template.
Thank you for your help! :)

**Comment by apozohue10** [comment]
Hi sickboy93,

To solve that problem, you need to create an application through the idm portal and then register a PEP Proxy in that application. You will obtain the username and password parameters which are the ones that you have to configure in the Wilma Pep Proxy.

You can find more information of how to do that here: [https://edu.fiware.org/course/view.php?id=131](url)

**Comment by sickboy93** [comment]
For now I didn't configured horizon (I've got some issue because I have all these VM in Openstack), so I'm using Keystone API.

I created an application(consumer, is that right?)
`curl --include \
     --request POST \
     --header "Content-Type: application/json" \
     --header "X-Auth-token: coritel" \
     --data-binary "{
  \"consumer\": {
    \"name\": \"test_app\",
    \"description\": \"my test app\",
    \"client_type\": \"confidential\",
    \"redirect_uris\": [
      \"http://localhost/login\"
    ],
    \"grant_type\": \"authorization_code\",
    \"scopes\": [
      \"all_info\"
    ]
  }
}" \
'http://localhost:5000/v3/OS-OAUTH2/consumers'`

How can I register the PEP proxy now?

**Comment by apozohue10** [comment]
I see. So for the user you have already created you need to assign the role pep_proxy to the user. To do that you need to obtain the id of the pep_proxy role from the list of roles:
_curl --include --header "X-Auth-token: YOUR_TOKEN" 'http://172.18.0.6:5000/v3/roles'_

And use the id to assign the role to the user:

curl --include --request PUT --header "X-Auth-token: YOUR_TOKEN" 'http://172.18.0.6:5000/v3/domains/default/users/USER_ID/roles/PEP_PROXY_ROLE_ID'

This should work

**Comment by sickboy93** [comment]
I don't have pep_proxy role:
`{
    "links": {
        "next": null,
        "previous": null,
        "self": "http://localhost:5000/v3/roles"
    },
    "roles": [
        {
            "id": "3bfb3210ef42432ca975cd6f842426de",
            "links": {
                "self": "http://localhost:5000/v3/roles/3bfb3210ef42432ca975cd6f842426de"
            },
            "name": "member"
        },
        {
            "id": "ca4b75557f1940bd99ef53e280d68db0",
            "links": {
                "self": "http://localhost:5000/v3/roles/ca4b75557f1940bd99ef53e280d68db0"
            },
            "name": "owner"
        },
        {
            "id": "857a5c2a3fec4eb188fddbf155068ebf",
            "is_default": true,
            "links": {
                "self": "http://localhost:5000/v3/roles/857a5c2a3fec4eb188fddbf155068ebf"
            },
            "name": "trial"
        },
        {
            "id": "80a660f2932543cb874b1a3e91fd7ffe",
            "is_default": true,
            "links": {
                "self": "http://localhost:5000/v3/roles/80a660f2932543cb874b1a3e91fd7ffe"
            },
            "name": "basic"
        },
        {
            "id": "9e76adc381d549d0b70be593eb06a8bc",
            "is_default": true,
            "links": {
                "self": "http://localhost:5000/v3/roles/9e76adc381d549d0b70be593eb06a8bc"
            },
            "name": "community"
        },
        {
            "id": "faa1a525ea734389b72a35c80cd046a4",
            "is_default": true,
            "links": {
                "self": "http://localhost:5000/v3/roles/faa1a525ea734389b72a35c80cd046a4"
            },
            "name": "admin"
        }
    ]
}
`
I tried to create it
`curl localhost:5000/v3/roles -H "X-Auth-Token: coritel" \
-d @- <<EOF
{
    "role": {
        "domain_id": "default",
        "name": "pep_proxy"
    }
}
EOF`

But 
`{"error": {"message": "create_role() got an unexpected keyword argument 'token_request'", "code": 400, "title": "Bad Request"}}`

I tried it even with a generated token and without that. If I don't put the header I have
`{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}`

**Comment by apozohue10** [comment]
There is another way, you can create directly on the database. Install sqlite3 and run this sql statments:
Create pep_proxy role:
_insert into role (id, name, extra) values ('pep_proxy', 'pep_proxy', '{"is_default": "true"}');_

Create assignment between role and user:
_insert into assignment (type, actor_id, target_id, role_id, inherited) values ('GroupDomain', 'USER_ID', 'default', 'pep_proxy', 0);_

This should do the trick.

**Comment by sickboy93** [comment]
All right it works, be careful that the user must have admin and pep_proxy roles, then you have to generate the token and finally start PEP.

Thank you for your help @apozohue10 !
