### ISSUE TITLE
Link not available

### ISSUE THREAD

**Issue by flopezag** [ging/fiware-pep-proxy#45]
The readthedoc documentation, specially the admin guide section, system installation. We can read the following content:

The username/password corresponds with the credentials of a registerd PEP Proxy in the FIWARE Account Portal. Do do so you have to first register an application. The steps can be found [here].

here makes reference to a link to the content http://fiware-idm.readthedocs.org/en/latest/user_guide.html#registering-an-application which does not exist. I think that It should be http://fiware-idm.readthedocs.io/en/latest/user_guide/#def-register-pep-and-iot

**Comment by aalonsog** [comment]
Fixed in https://github.com/ging/fiware-pep-proxy/pull/46
