### ISSUE TITLE
Add 401 if token is invalid for release 5.3.1

### ISSUE THREAD

**Issue by caa06d9c** [ging/fiware-pep-proxy#58]
Please, add the same functionality as described [here](https://github.com/ging/fiware-pep-proxy/issues/54) to the old release 5.3.1. This release works with orion global instance.

**Comment by aalonsog** [comment]
Hi @caa06d9c, that is a very old release of the component that have dependencies problems with the current Node.js version. I recommend you to update it in the orion global instance.
