### ISSUE TITLE
Error protecting resources with invalid XML parameters

### ISSUE THREAD

**Issue by albertinisg** [ging/fiware-pep-proxy#7]
Hi!

We are using IdM, Authzforce and Wilma PEP environment to protect our app and, we are having issues protecting some resources. 

For example, we are trying to protect the resource `NGSI10/queryContext?limit=1000&entity_type=review`, but when doing the request against Authzforce it throws the following error:

```
[AZF] Checking authorization to roles [ '2e11644af92047a18474e849d6747b9a' ] to do  POST  on  NGSI10/queryContext?limit=1000&entity_type=review and app  d5f5eec653a540d996b6e1f562ed7e70
Error in AZF communication  <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:error xmlns:ns2="http://thalesgroup.com/authz/model/3.0" xmlns:ns3="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:ns4="http://thalesgroup.com/authzforce/pdp/model/2014/12"><message>Unexpected character '=' (code 61); expected a semi-colon after the reference for entity 'entity_type'
 at [row,col {unknown-source}]: [1,999]</message></ns2:error>
```

This error is caused due to the character `&`, which is forbidden in XML. Encoding the forbidden characters in the `resource` parameter would solve any issues like this one, as IdM already encodes this request against authzforce.

**Comment by aalonsog** [comment]
Thanks! I will take a look.

**Comment by aalonsog** [comment]
Fixed!

**Comment by albertinisg** [comment]
Great! Thanks a lot :smile:
