### ISSUE TITLE
[Docker Compose] Proxy configuration with ENV variables

### ISSUE THREAD

**Issue by gabrieledeluca** [ging/fiware-pep-proxy#70]
Following PEP Proxy Configuration ("SECURING ORION - PEP PROXY CONFIGURATION") at https://fiware-tutorials.readthedocs.io/en/stable/pep-proxy/index.html I receive this error:
`
fiware-pep_1  | TypeError: Cannot read property 'secret' of undefined 
fiware-pep_1  |     at pep (/opt/fiware-pep-proxy/controllers/root.js:61:34)
`

**Comment by jason-fox** [comment]
This issue is addressed in PR #66  - specifically the Docker instance is currently loading a file which does not contain a `secret` attribute.

**Comment by jason-fox** [comment]
Since PR #66 has been merged, this should now be fixed.

**Comment by aalonsog** [comment]
Great!
