### ISSUE TITLE
Why there is `trusted_apps` setting in pep-proxy

### ISSUE THREAD

**Issue by TK009** [ging/fiware-pep-proxy#85]
When using Keyrock idm as the pdp, the pep-proxy checks that the user is logged in from `pep.trusted_apps` ([line 114](https://github.com/ging/fiware-pep-proxy/blob/c6437e00b3bc038b776d61c04622e71d7640ad9a/lib/idm.js#L114) and [214](https://github.com/ging/fiware-pep-proxy/blob/c6437e00b3bc038b776d61c04622e71d7640ad9a/lib/idm.js#L214)). Is there a reason to do this? Because Keyrock already has a "trusted applications" list, doesn't it already check the user permissions and app_id there?

Now I need to add new trusted apps to both lists in idm and pep-proxy. This is a problem for me because  it needs a manual configuration edit and restart for pep-proxy.

**Comment by apozohue10** [comment]
Sorry for the delay in answering. [PR 111](https://github.com/ging/fiware-pep-proxy/pull/111) has solved this issue
