### ISSUE TITLE
Use toBoolean with PEP_PROXY_ORG_ENABLED

### ISSUE THREAD

**Issue by minimalisti** [ging/fiware-pep-proxy#87]
https://github.com/ging/fiware-pep-proxy/blob/767d5abee89370c8ed3a3d74758da920d8578bef/config.js.template#L31

I had some trouble with not being able to disable the organization header checking by setting the environment variable _PEP_PROXY_ORG_ENABLED_ to false. But when I changed the _config.js_ by changing _config.organizations_ to:

```
config.organizations = {
  enabled: toBoolean(process.env.PEP_PROXY_ORG_ENABLED, false),
  header: process.env.PEP_PROXY_ORG_HEADER || 'fiware-service'
}
```

everything worked. It seems that using toBoolean function was needed.

**Comment by apozohue10** [comment]
Thank you for the comment! we will include this fix in the following release
