### ISSUE TITLE
Missing Fiware-Service Header in Allowed Auth Header on CORS Preflight request

### ISSUE THREAD

**Issue by Siedlerchr** [ging/fiware-pep-proxy#93]
Hi,
I am currently facing an http error when trying to acess an ORION instance behind a PEP/Keyrock proxy instance from my javascript app running on localhost which uses the [Fiware-Service](https://fiware-orion.readthedocs.io/en/master/user/service_path/index.html) header.

> Reason: missing token ‘fiware-service’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel

Requests without the `fiware-service` header are working.
https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight?utm_source=devtools&utm_medium=firefox-cors-error

`http://<fiware-orion-instance>:1027/v2/entities?type=WaterLevel&options=keyValues,count&attrs=name&limit=200`

My Auth headers:
```
Host: <fiware-orion-instance>:1027
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,fiware-service
Referer: http://localhost:8100/tabs/tab2
Origin: http://localhost:8100
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```
Server Response:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, POST, PUT, GET, OPTIONS, DELETE
Access-Control-Allow-Headers: origin, content-type, X-Auth-Token, Tenant-ID, Authorization
Content-Length: 0
Date: Tue, 29 Oct 2019 08:42:47 GMT
Connection: keep-alive
```
The solution would be to simply add the header to this list here or to add a configuration option.

https://github.com/ging/fiware-pep-proxy/blob/554f20c982fe1bcba0169d17ba389be3d5b68828/server.js#L49

**Comment by apozohue10** [comment]
Fixed by your PR #95
