### ISSUE TITLE
Running docker container as non-root user

### ISSUE THREAD

**Issue by SamuelTJackson** [ging/fiware-pep-proxy#96]
Hey,
if I try to start the fiware/pep-proxy container with a different user than root (e.g. user: "994:993") I get the following error:

> npm update check failed
> Try running with sudo or get access
> to the local update config store via
> sudo chown -R $USER:$(id -gn $USER) /.config

Do I now have to build my own image and change the permissions in it or is there a solution without having to build my own image?

Is it possible to work with docker secrets for the environment variable `PEP_PASSWORD`. For example `PEP_PASSWORD_FILE`

**Comment by apozohue10** [comment]
Hi @SamuelTJackson 

I think that the error is due to the permission on your machine. But if it persists try to build your own image.

Now you can use docker secrets. You can see how to use them by checking extras/docker/docker-entrypoint.sh
